### ISSUE TITLE
What is this project?

### ISSUE THREAD

**Issue by NoahRoseLedesma** [post-programming/post-programming#1]
The more I read the README.md, the more I think that this project must be some drawn out satire.  If i'm wrong, then your README is not doing a good job at communicating what this project is. To me, it just sounds like a hodgepodge of buzzwords loosely strapped together.

So... What is this? My curiosity has been peaked.

**Comment by prateekrastogi** [comment]
it is "post-programming" if that word itself is considered in modern tech literature contagion

**Comment by prateekrastogi** [comment]
Given the fact that a lot has changed, as can be seen in the git history of this repo itself, since that issue was opened, I would like to make some immutable remarks convexing limelight of media attention on my invention i.e. "Post-Programming"

**Comment by prateekrastogi** [comment]
* As the Git repo itself has become solely focused on "Post-Programming", henceforth, it will be `immutable` for the purpose of inducing consolidation of facts mentioned herein, as in. 
* As far as insidious contents of hyperlinks on my painting i.e. 'homepage of post-programming.com' is concerned, they are nothing but `Pointillé of Hyperspaces` for assisting additive construction of 'Post-Programming' in Neo-Impressionists audience such as 'professional programmers' itself.

**Comment by prateekrastogi** [comment]
*  However, even after lockdown of this repo git content, I will be monitoring upended issues opened here for credit blackouts or credit default swap on this briefest birth/summation of `Post-Programming`

**Comment by prateekrastogi** [comment]
*  However, even after lockdown of this repo git content, I will be monitoring upended issues opened here for credit blackouts or credit default swap on this briefest birth/summation of 
`Post-Programming`

**Comment by prateekrastogi** [comment]
* However, even after lockdown of this repo git content, I will be monitoring upended issues opened here for credit blackouts or credit default swaps on this briefest birth/summation of
`Post-Programming`
